// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_permute_tree
Rcpp::List cpp_permute_tree(Rcpp::List tree_list);
RcppExport SEXP _TreeCalcs_cpp_permute_tree(SEXP tree_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type tree_list(tree_listSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_permute_tree(tree_list));
    return rcpp_result_gen;
END_RCPP
}
// cpp_traverse_tree
Rcpp::DataFrame cpp_traverse_tree(Rcpp::List tree_list);
RcppExport SEXP _TreeCalcs_cpp_traverse_tree(SEXP tree_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type tree_list(tree_listSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_traverse_tree(tree_list));
    return rcpp_result_gen;
END_RCPP
}
// cpp_propagate_tree
Rcpp::List cpp_propagate_tree(Rcpp::List tree_list, std::string op);
RcppExport SEXP _TreeCalcs_cpp_propagate_tree(SEXP tree_listSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type tree_list(tree_listSEXP);
    Rcpp::traits::input_parameter< std::string >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_propagate_tree(tree_list, op));
    return rcpp_result_gen;
END_RCPP
}
// cpp_fold_tree
double cpp_fold_tree(Rcpp::List tree_list, std::string op);
RcppExport SEXP _TreeCalcs_cpp_fold_tree(SEXP tree_listSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type tree_list(tree_listSEXP);
    Rcpp::traits::input_parameter< std::string >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_fold_tree(tree_list, op));
    return rcpp_result_gen;
END_RCPP
}
// cpp_tree_to_string
std::string cpp_tree_to_string(Rcpp::List tree_list);
RcppExport SEXP _TreeCalcs_cpp_tree_to_string(SEXP tree_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type tree_list(tree_listSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_tree_to_string(tree_list));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cshapley
Rcpp::NumericVector cpp_cshapley(Rcpp::List tree_list, Rcpp::Function calc_func);
RcppExport SEXP _TreeCalcs_cpp_cshapley(SEXP tree_listSEXP, SEXP calc_funcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type tree_list(tree_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type calc_func(calc_funcSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cshapley(tree_list, calc_func));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TreeCalcs_cpp_permute_tree", (DL_FUNC) &_TreeCalcs_cpp_permute_tree, 1},
    {"_TreeCalcs_cpp_traverse_tree", (DL_FUNC) &_TreeCalcs_cpp_traverse_tree, 1},
    {"_TreeCalcs_cpp_propagate_tree", (DL_FUNC) &_TreeCalcs_cpp_propagate_tree, 2},
    {"_TreeCalcs_cpp_fold_tree", (DL_FUNC) &_TreeCalcs_cpp_fold_tree, 2},
    {"_TreeCalcs_cpp_tree_to_string", (DL_FUNC) &_TreeCalcs_cpp_tree_to_string, 1},
    {"_TreeCalcs_cpp_cshapley", (DL_FUNC) &_TreeCalcs_cpp_cshapley, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_TreeCalcs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
