# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Permute all subtrees of a tree in C++
#' 
#' Generates all valid permutations of children at each internal node level.
#' 
#' @param tree_list A nested list representing the tree hierarchy.
#' @return A list of nested lists representing all permuted trees.
#' @export
cpp_permute_tree <- function(tree_list) {
    .Call(`_TreeCalcs_cpp_permute_tree`, tree_list)
}

#' Traverse a tree and extract leaf keys and values
#' 
#' Performs in-order type-aware traversal on the tree.
#' 
#' @param tree_list A nested list representing the tree hierarchy.
#' @return A DataFrame with columns 'key' and 'value'.
#' @export
cpp_traverse_tree <- function(tree_list) {
    .Call(`_TreeCalcs_cpp_traverse_tree`, tree_list)
}

#' Propagate values from leaves up to internal nodes
#' 
#' Computes internal node values by applying an aggregation operation
#' over children values recursively.
#' 
#' @param tree_list A nested list representing the tree hierarchy.
#' @param op Aggregation operator: 'sum', 'prod', 'mean', 'max', or 'min'.
#' @return A new nested list with internal node values populated.
#' @export
cpp_propagate_tree <- function(tree_list, op = "sum") {
    .Call(`_TreeCalcs_cpp_propagate_tree`, tree_list, op)
}

#' Fold a tree using aggregation functions
#' 
#' Recursively reduces the tree from leaves to a single scalar result.
#' 
#' @param tree_list A nested list representing the tree hierarchy.
#' @param op Reduction operator: 'sum', 'prod', 'mean', 'max', 'min', or 'count'.
#' @return A numeric scalar with the folded result.
#' @export
cpp_fold_tree <- function(tree_list, op = "sum") {
    .Call(`_TreeCalcs_cpp_fold_tree`, tree_list, op)
}

#' Generate ASCII visual representation of a tree
#' 
#' @param tree_list A nested list representing the tree hierarchy.
#' @return A character string showing the ASCII tree.
#' @export
cpp_tree_to_string <- function(tree_list) {
    .Call(`_TreeCalcs_cpp_tree_to_string`, tree_list)
}

#' Compute hierarchical cShapley values for tree leaves
#' 
#' @param tree_list A nested list representing the tree hierarchy.
#' @param calc_func An R function taking a DataFrame of leaves with columns 'key' and 'value'.
#' @return A named numeric vector of Shapley values for each leaf.
#' @export
cpp_cshapley <- function(tree_list, calc_func) {
    .Call(`_TreeCalcs_cpp_cshapley`, tree_list, calc_func)
}

